name: CD
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout from repository
      uses: actions/checkout@v2
      with:
        repository: 'mystroken/mystroken.com'
        token: ${{ secrets.MYSTROKEN_WEBSITE_PAT }}

    - name: Push on the server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST  }}
        username: ${{ secrets.USERNAME  }}
        key: ${{ secrets.SSHKEY  }}
        port: ${{ secrets.PORT  }}
        script: |
          cd ${{ secrets.PROJECT_PATH  }}
          git pull

    - name: Build the app
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST  }}
        username: ${{ secrets.USERNAME  }}
        key: ${{ secrets.SSHKEY  }}
        port: ${{ secrets.PORT  }}
        script: |
          cd ${{ secrets.PROJECT_PATH  }}
          cd ../../
          docker-compose build mystroken_gatsby
          docker-compose up -d
